apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-2
  version: "1.21"

iam:
  withOIDC: true

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group-spot-instances
    desiredCapacity: 3
    privateNetworking: true
    amiFamily: Bottlerocket
    instancesDistribution:
      instanceTypes: ["t3.medium", "t3a.medium"]
      onDemandPercentageAboveBaseCapacity: 0
    labels: { lifecycle: Ec2Spot }