apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: environments-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  labels:
    app: {{ template "services-api.name" . }}
    release: {{ .Release.Name }}
spec:
  rules:
    - host: services-api-{{ .Release.Namespace }}.{{ .Values.baseDomain }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ template "services-api.name" . }}
              servicePort: {{ .Values.service.port }}